"""timezone change logs

Revision ID: 0087400beb85
Revises: ad7ac4e91d81
Create Date: 2024-11-06 19:38:14.631274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0087400beb85'
down_revision: Union[str, None] = 'ad7ac4e91d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_logs_driver_name', table_name='logs')
    op.drop_index('ix_logs_uid', table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('driver_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('transaction_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason_of_abend', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raised_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('fixed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('closed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('open', 'closed', 'attending', name='log_status'), autoincrement=False, nullable=False),
    sa.Column('attending_person', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['attending_person'], ['users.id'], name='logs_attending_person_fkey'),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], name='logs_closed_by_fkey'),
    sa.PrimaryKeyConstraint('uid', name='logs_pkey')
    )
    op.create_index('ix_logs_uid', 'logs', ['uid'], unique=False)
    op.create_index('ix_logs_driver_name', 'logs', ['driver_name'], unique=False)
    # ### end Alembic commands ###
