"""user-password

Revision ID: 861d7005c0c0
Revises: e063d585e12c
Create Date: 2024-10-29 16:16:55.606036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '861d7005c0c0'
down_revision: Union[str, None] = 'e063d585e12c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
