"""user-password-2

Revision ID: de9f621a6df8
Revises: 861d7005c0c0
Create Date: 2024-10-29 16:26:00.983481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'de9f621a6df8'
down_revision: Union[str, None] = '861d7005c0c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
