"""init

Revision ID: fb2a3cb78f41
Revises: 
Create Date: 2024-10-26 15:25:16.139178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fb2a3cb78f41'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'notification_token',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'notification_token',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
